import { boolean, date, index, integer, jsonb, numeric, pgEnum, pgTable, primaryKey, text, timestamp, unique, uuid, varchar } from "drizzle-orm/pg-core";

const id = () => uuid("id").defaultRandom().primaryKey();
const timestamps = { createdAt: timestamp("created_at", { withTimezone:true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone:true }).notNull().defaultNow() };

export const membershipRole = pgEnum("membership_role", ["school_admin","principal","vice_principal","bursar","teacher","parent","student"]);
export const paymentStatus = pgEnum("payment_status", ["pending_approval","approved","rejected"]);
export const paymentMethod = pgEnum("payment_method", ["cash","transfer"]);
export const attendanceStatus = pgEnum("attendance_status", ["present","absent","late","excused"]);
export const notificationChannel = pgEnum("notification_channel", ["in_app","email","sms"]);
export const notificationStatus = pgEnum("notification_status", ["queued","sent","delivered","failed"]);

// Better Auth tables. Generated by `npm run auth:generate`, then moved here so all tables live in one schema.
export const users = pgTable("users", { id: text("id").primaryKey(), name:text("name").notNull(), email:text("email").unique(), emailVerified:boolean("email_verified").notNull().default(false), image:text("image"), accountType:text("account_type").notNull().default("student"), username:text("username").unique(), displayUsername:text("display_username"), isPlatformAdmin:boolean("is_platform_admin").notNull().default(false), createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(), updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow() });

export const sessions = pgTable("sessions", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at").notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").$onUpdate(() => new Date()).notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
}, (t) => [index("sessions_userId_idx").on(t.userId)]);

export const accounts = pgTable("accounts", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").$onUpdate(() => new Date()).notNull(),
}, (t) => [index("accounts_userId_idx").on(t.userId)]);

export const verifications = pgTable("verifications", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()).notNull(),
}, (t) => [index("verifications_identifier_idx").on(t.identifier)]);

export const schools = pgTable("schools", { id:id(), name:varchar("name",{length:180}).notNull(), slug:varchar("slug",{length:120}).notNull().unique(), schoolCode:text("school_code").notNull().unique(), email:varchar("email",{length:254}), phone:varchar("phone",{length:40}), address:text("address"), state:varchar("state",{length:120}), country:varchar("country",{length:120}), logoKey:text("logo_key"), timezone:varchar("timezone",{length:64}).notNull().default("Africa/Lagos"), currency:varchar("currency",{length:3}).notNull().default("NGN"), requireApproval:boolean("require_approval").notNull().default(false), ...timestamps });
export const memberships = pgTable("memberships", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), userId:text("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), role:membershipRole("role").notNull(), canApprovePayments:boolean("can_approve_payments").notNull().default(false), canReleaseResults:boolean("can_release_results").notNull().default(false), ...timestamps },t=>[unique("memberships_school_user_unique").on(t.schoolId,t.userId),index("memberships_school_idx").on(t.schoolId)]);
export const academicSessions = pgTable("academic_sessions", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), name:varchar("name",{length:80}).notNull(), startsOn:date("starts_on").notNull(), endsOn:date("ends_on").notNull(), isCurrent:boolean("is_current").notNull().default(false), ...timestamps },t=>[unique("session_school_name_unique").on(t.schoolId,t.name)]);
export const terms = pgTable("terms", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), academicSessionId:uuid("academic_session_id").notNull().references(()=>academicSessions.id,{onDelete:"cascade"}), name:varchar("name",{length:80}).notNull(), sequence:integer("sequence").notNull(), startsOn:date("starts_on").notNull(), endsOn:date("ends_on").notNull(), ...timestamps },t=>[unique("term_session_sequence_unique").on(t.academicSessionId,t.sequence),index("terms_school_idx").on(t.schoolId)]);
export const classes = pgTable("classes", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), name:varchar("name",{length:120}).notNull(), level:varchar("level",{length:60}), ...timestamps },t=>[unique("classes_school_name_unique").on(t.schoolId,t.name)]);
export const streams = pgTable("streams", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), classId:uuid("class_id").notNull().references(()=>classes.id,{onDelete:"cascade"}), name:varchar("name",{length:80}).notNull(), ...timestamps },t=>[unique("streams_class_name_unique").on(t.classId,t.name)]);
export const students = pgTable("students", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), admissionNo:varchar("admission_no",{length:80}).notNull(), firstName:varchar("first_name",{length:100}).notNull(), lastName:varchar("last_name",{length:100}).notNull(), middleName:varchar("middle_name",{length:100}), dateOfBirth:date("date_of_birth"), guardianPhone:varchar("guardian_phone",{length:40}), guardianEmail:varchar("guardian_email",{length:254}), photoKey:text("photo_key"), className:varchar("class_name",{length:80}), profile:jsonb("profile").notNull().default({}), userId:text("user_id").references(()=>users.id), streamId:uuid("stream_id").references(()=>streams.id), ...timestamps },t=>[unique("students_school_admission_unique").on(t.schoolId,t.admissionNo),index("students_school_idx").on(t.schoolId)]);
// Per-school, per-year counter for student IDs (YY-NNNNN). Incremented atomically
// via an upsert (ON CONFLICT DO UPDATE) so concurrent student creation is race-safe.
export const studentSequences = pgTable("student_sequences", {
  schoolId: uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}),
  year: integer("year").notNull(),
  lastSeq: integer("last_seq").notNull().default(0),
  ...timestamps,
}, t=>[primaryKey({ columns:[t.schoolId, t.year] })]);

export const staffProfiles = pgTable("staff_profiles", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), userId:text("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), staffNo:varchar("staff_no",{length:80}), gatePinHash:text("gate_pin_hash"), employmentType:varchar("employment_type",{length:30}), jobRole:varchar("job_role",{length:60}), startDate:date("start_date"), status:varchar("status",{length:20}).notNull().default("pending"), isTeacher:boolean("is_teacher").notNull().default(false), isClassTeacher:boolean("is_class_teacher").notNull().default(false), assignedClass:varchar("assigned_class",{length:80}), subjects:jsonb("subjects").notNull().default([]), teachingClasses:jsonb("teaching_classes").notNull().default([]), permissions:jsonb("permissions").notNull().default({}), inviteToken:text("invite_token").unique(), profile:jsonb("profile").notNull().default({}), ...timestamps },t=>[unique("staff_school_user_unique").on(t.schoolId,t.userId)]);
export const parentStudents = pgTable("parent_students", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), parentUserId:text("parent_user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), studentId:uuid("student_id").notNull().references(()=>students.id,{onDelete:"cascade"}), relationship:varchar("relationship",{length:60}), ...timestamps },t=>[unique("parent_student_unique").on(t.parentUserId,t.studentId)]);
export const auditLogs = pgTable("audit_logs", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), actorUserId:text("actor_user_id").references(()=>users.id), action:varchar("action",{length:160}).notNull(), entityType:varchar("entity_type",{length:100}).notNull(), entityId:varchar("entity_id",{length:100}), metadata:jsonb("metadata").notNull().default({}), ipAddress:varchar("ip_address",{length:64}), createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow() },t=>[index("audit_logs_school_created_idx").on(t.schoolId,t.createdAt)]);

export const teacherGateCheckins = pgTable("teacher_gate_checkins", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), staffProfileId:uuid("staff_profile_id").notNull().references(()=>staffProfiles.id,{onDelete:"cascade"}), checkedInAt:timestamp("checked_in_at",{withTimezone:true}).notNull().defaultNow(), method:varchar("method",{length:30}).notNull(), deviceId:varchar("device_id",{length:160}), status:varchar("status",{length:30}).notNull(), ...timestamps },t=>[index("gate_checkin_school_time_idx").on(t.schoolId,t.checkedInAt)]);
export const attendanceRecords = pgTable("attendance_records", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), studentId:uuid("student_id").notNull().references(()=>students.id,{onDelete:"cascade"}), termId:uuid("term_id").notNull().references(()=>terms.id), attendanceDate:date("attendance_date").notNull(), status:attendanceStatus("status").notNull().default("present"), markedByUserId:text("marked_by_user_id").references(()=>users.id), lateAt:timestamp("late_at",{withTimezone:true}), ...timestamps },t=>[unique("attendance_student_date_unique").on(t.studentId,t.attendanceDate),index("attendance_school_date_idx").on(t.schoolId,t.attendanceDate)]);
export const payments = pgTable("payments", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), studentId:uuid("student_id").notNull().references(()=>students.id), termId:uuid("term_id").references(()=>terms.id), invoiceId:uuid("invoice_id"), amount:numeric("amount",{precision:14,scale:2}).notNull(), method:paymentMethod("method").notNull(), status:paymentStatus("status").notNull().default("pending_approval"), description:text("description"), receiptKey:text("receipt_key"), proofKey:text("proof_key"), recordedByUserId:text("recorded_by_user_id").notNull().references(()=>users.id), approvedByUserId:text("approved_by_user_id").references(()=>users.id), approvedAt:timestamp("approved_at",{withTimezone:true}), rejectedReason:text("rejected_reason"), ...timestamps },t=>[index("payments_school_status_idx").on(t.schoolId,t.status)]);
export const feeStructures = pgTable("fee_structures", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), name:varchar("name",{length:120}).notNull(), termLabel:varchar("term_label",{length:80}), amount:numeric("amount",{precision:14,scale:2}).notNull(), appliesTo:varchar("applies_to",{length:80}).notNull().default("all"), classes:jsonb("classes").notNull().default([]), ...timestamps });
export const invoices = pgTable("invoices", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), studentId:uuid("student_id").notNull().references(()=>students.id,{onDelete:"cascade"}), feeStructureId:uuid("fee_structure_id").references(()=>feeStructures.id,{onDelete:"set null"}), description:varchar("description",{length:160}), amount:numeric("amount",{precision:14,scale:2}).notNull(), status:varchar("status",{length:20}).notNull().default("outstanding"), dueDate:date("due_date"), ...timestamps },t=>[index("invoices_school_idx").on(t.schoolId)]);

export const bankDeposits = pgTable("bank_deposits", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), depositedOn:date("deposited_on").notNull(), amount:numeric("amount",{precision:14,scale:2}).notNull(), reference:varchar("reference",{length:160}), recordedByUserId:text("recorded_by_user_id").references(()=>users.id), ...timestamps });
export const notifications = pgTable("notifications", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), recipientUserId:text("recipient_user_id").references(()=>users.id), studentId:uuid("student_id").references(()=>students.id), channel:notificationChannel("channel").notNull(), status:notificationStatus("status").notNull().default("queued"), template:varchar("template",{length:120}), payload:jsonb("payload").notNull().default({}), cost:numeric("cost",{precision:12,scale:2}).notNull().default("0"), sentAt:timestamp("sent_at",{withTimezone:true}), ...timestamps });

// Phase 2 schema seams. These tables are deliberately modelled now but are not surfaced in the MVP runtime.
export const gradingScales = pgTable("grading_scales", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), name:varchar("name",{length:120}).notNull(), isDefault:boolean("is_default").notNull().default(false), ...timestamps });
export const gradeBands = pgTable("grade_bands", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), gradingScaleId:uuid("grading_scale_id").notNull().references(()=>gradingScales.id,{onDelete:"cascade"}), grade:varchar("grade",{length:16}).notNull(), remark:varchar("remark",{length:120}), minScore:numeric("min_score",{precision:5,scale:2}).notNull(), maxScore:numeric("max_score",{precision:5,scale:2}).notNull(), ...timestamps });
export const assessmentSchemes = pgTable("assessment_schemes", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), gradingScaleId:uuid("grading_scale_id").notNull().references(()=>gradingScales.id), name:varchar("name",{length:120}).notNull(), ...timestamps });
export const assessmentComponents = pgTable("assessment_components", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), assessmentSchemeId:uuid("assessment_scheme_id").notNull().references(()=>assessmentSchemes.id,{onDelete:"cascade"}), category:varchar("category",{length:12}).notNull(), name:varchar("name",{length:120}).notNull(), maxScore:numeric("max_score",{precision:5,scale:2}).notNull(), ...timestamps });
export const examSessions = pgTable("exam_sessions", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), studentId:uuid("student_id").notNull().references(()=>students.id), startsAt:timestamp("starts_at",{withTimezone:true}).notNull(), endsAt:timestamp("ends_at",{withTimezone:true}).notNull(), status:varchar("status",{length:30}).notNull(), lastSeenAt:timestamp("last_seen_at",{withTimezone:true}), ...timestamps });
// Overpayment refund requests. When a student's approved payments exceed what they were billed, the
// credit can be carried forward (default) or refunded — a refund needs a designated approver.
export const refundRequests = pgTable("refund_requests", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), studentId:uuid("student_id").notNull().references(()=>students.id,{onDelete:"cascade"}), amount:numeric("amount",{precision:14,scale:2}).notNull(), reason:text("reason"), status:varchar("status",{length:20}).notNull().default("pending"), requestedByUserId:text("requested_by_user_id").references(()=>users.id), approvedByUserId:text("approved_by_user_id").references(()=>users.id), decidedAt:timestamp("decided_at",{withTimezone:true}), ...timestamps },t=>[index("refund_requests_school_status_idx").on(t.schoolId,t.status)]);
// Per-subject, per-term result for a student. CA out of 40 + Exam out of 60 = 100 (standard Nigerian split).
export const studentResults = pgTable("student_results", { id:id(), schoolId:uuid("school_id").notNull().references(()=>schools.id,{onDelete:"cascade"}), studentId:uuid("student_id").notNull().references(()=>students.id,{onDelete:"cascade"}), term:varchar("term",{length:80}).notNull(), subject:varchar("subject",{length:120}).notNull(), ca:integer("ca").notNull().default(0), exam:integer("exam").notNull().default(0), ...timestamps },t=>[unique("student_result_unique").on(t.studentId,t.term,t.subject),index("student_results_school_term_idx").on(t.schoolId,t.term)]);